export const SET_SUCCESS_MSG = "SET_SUCCESS_MSG";
export const SHOW_SUCCESS_MSG = "SHOW_SUCCESS_MSG";
export const HIDE_SUCCESS_MSG = "HIDE_SUCCESS_MSG";

export const SET_USER_AUTH_TOKEN = "SET_USER_AUTH_TOKEN";
export const SET_USER_NICKNAME = "SET_USER_NICKNAME";
export const RESET_USER_NICKNAME = "RESET_USER_NICKNAME";
export const RESET_USER_AUTH_TOKEN = "RESET_USER_AUTH_TOKEN";
